services:
  traefik:
    image: traefik:latest
    container_name: traefik
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config/dynamic.yaml:/etc/traefik/dynamic.yaml
      - ./config/traefik.yaml:/etc/traefik/traefik.yaml:ro
      - ./ssl:/etc/traefik/ssl
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    command:
      - "--entryPoints.web.address=:80"
      - "--entryPoints.websecure.address=:443"
    networks:
      - traefik
    restart: unless-stopped
networks:
  traefik:
    external: true
