services:
  example:
    image: wordpress:php8.3
    container_name: example_wp
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./html:/var/www/html
      - ./.env:/var/www/.env:ro
      - ./config/php/php.ini:/usr/local/etc/php/conf.d/000-global.ini
    ports:
      - "8081:80"
    env_file:
      - ./.env
    environment:
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_HOME', 'https://${ROOT_URL}');
        define('WP_SITEURL', 'https://${ROOT_URL}');
        define('WP_DEBUG', ${WORDPRESS_DEBUG});
        define('WP_DEBUG_DISPLAY', ${WORDPRESS_DEBUG_DISPLAY});
        define('WP_DEBUG_LOG', ${WORDPRESS_DEBUG_LOG});
        define('WP_CACHE', ${WORDPRESS_CACHE});
        define('WP_ENVIRONMENT_TYPE', '${WORDPRESS_ENVIRONMENT_TYPE}');
        define('WP_DEVELOPMENT_MODE', '${WORDPRESS_DEVELOPMENT_MODE}');
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - 'traefik.http.routers.examplewp.rule=Host("${ROOT_URL}")'
      - "traefik.http.services.examplewp.loadbalancer.server.port=80"
    depends_on:
      - db
    extra_hosts:
      - "${ROOT_URL}:host-gateway"
    restart: unless-stopped

  db:
    image: mysql:latest
    container_name: example_wp_db
    env_file:
      - ./.env
    volumes:
      - ./data:/data
    networks:
      - traefik
    command:
      - "--skip-log-bin"
    restart: unless-stopped

volumes:
  data: {}
  db_data: {}

networks:
  traefik:
    external: true
