global:
  checkNewVersion: false
  sendAnonymousUsage: false

tls:
  certificates:
    - certFile: "/etc/traefik/ssl/sites.crt"
      keyFile: "/etc/traefik/ssl/sites.key"

http:
  middlewares:
    cors:
      headers:
        accessControlAllowOriginList:
          - "*"
        accessControlAllowMethods:
          - "GET"
          - "OPTIONS"
          - "PUT"
          - "POST"
          - "DELETE"
        accessControlAllowHeaders:
          - "Origin"
          - "Content-Type"
          - "Accept"
          - "Authorization"
        addVaryHeader: true
