entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: "websecure"
          scheme: "https"
          permanent: true
  websecure:
    address: ":443"
    http:
      tls: {}

api:
  insecure: false
  dashboard: false
  debug: true

providers:
  file:
    filename: "/etc/traefik/dynamic.yaml"

  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false

log:
  level: DEBUG
